"""NCERT/Haryana Board curriculum data for RAG retrieval."""

CURRICULUM = [
    # Science: Class 6-8
    {"id": "sci-6-food", "subject": "Science", "class_range": "6-8",
     "chapter": "Food: Where Does It Come From?", "topic": "Food sources",
     "keywords": ["food", "source", "plant", "animal", "ingredient", "crop", "nutrition"],
     "content": "Food comes from plants (grains, vegetables, fruits) and animals (milk, eggs, meat). Plants make their own food through photosynthesis. Animals depend on plants directly or indirectly."},
    {"id": "sci-6-components", "subject": "Science", "class_range": "6-8",
     "chapter": "Components of Food", "topic": "Nutrients",
     "keywords": ["nutrient", "carbohydrate", "protein", "fat", "vitamin", "mineral", "roughage"],
     "content": "Food contains nutrients: carbohydrates (energy), proteins (growth), fats (energy storage), vitamins and minerals (protection), and roughage (digestion). A balanced diet has all nutrients in right proportions."},
    {"id": "sci-6-plant-body", "subject": "Science", "class_range": "6-8",
     "chapter": "Getting to Know Plants", "topic": "Plant parts and functions",
     "keywords": ["plant", "root", "stem", "leaf", "flower", "photosynthesis", "chlorophyll"],
     "content": "Plants have roots (anchoring, absorption), stems (support, transport), leaves (photosynthesis using chlorophyll), and flowers (reproduction)."},
    {"id": "sci-6-motion", "subject": "Science", "class_range": "6-8",
     "chapter": "Motion and Measurement", "topic": "Types of motion",
     "keywords": ["motion", "movement", "distance", "speed", "rectilinear", "circular", "periodic", "oscillatory"],
     "content": "Motion is a change in position. Types: rectilinear (straight line), circular (circle), periodic (repeating), oscillatory (to-and-fro). SI unit of length is metre."},
    {"id": "sci-6-light", "subject": "Science", "class_range": "6-8",
     "chapter": "Light, Shadows and Reflections", "topic": "Light behavior",
     "keywords": ["light", "shadow", "reflection", "mirror", "opaque", "transparent", "translucent"],
     "content": "Light travels in straight lines. Opaque objects block light creating shadows. Mirrors reflect light. Transparent objects let light pass through."},
    {"id": "sci-6-electricity", "subject": "Science", "class_range": "6-8",
     "chapter": "Electricity and Circuits", "topic": "Simple circuits",
     "keywords": ["electricity", "circuit", "battery", "bulb", "switch", "conductor", "insulator"],
     "content": "An electric circuit needs a battery (power source), wires (conductors), a bulb (load), and a switch. Conductors allow current to flow; insulators do not."},
    {"id": "sci-7-nutrition", "subject": "Science", "class_range": "6-8",
     "chapter": "Nutrition in Plants and Animals", "topic": "Photosynthesis and digestion",
     "keywords": ["photosynthesis", "chlorophyll", "autotroph", "heterotroph", "digestion", "stomata"],
     "content": "Plants are autotrophs — they make food via photosynthesis using sunlight, water, CO2 and chlorophyll in leaves. Stomata on leaves allow gas exchange. Animals are heterotrophs."},
    {"id": "sci-7-heat", "subject": "Science", "class_range": "6-8",
     "chapter": "Heat", "topic": "Temperature and heat transfer",
     "keywords": ["heat", "temperature", "thermometer", "conduction", "convection", "radiation", "Celsius"],
     "content": "Heat is energy; temperature is a measure of hotness. Thermometers measure temperature in Celsius. Heat transfers by conduction (solids), convection (fluids), and radiation (no medium needed)."},
    {"id": "sci-7-acids", "subject": "Science", "class_range": "6-8",
     "chapter": "Acids, Bases and Salts", "topic": "Acids, bases and indicators",
     "keywords": ["acid", "base", "salt", "indicator", "litmus", "pH", "neutralization"],
     "content": "Acids taste sour (lemon, vinegar). Bases taste bitter (soap). Indicators like litmus change color: acids turn blue litmus red, bases turn red litmus blue. Neutralization forms salt and water."},
    {"id": "sci-8-force", "subject": "Science", "class_range": "6-8",
     "chapter": "Force and Pressure", "topic": "Force types and pressure",
     "keywords": ["force", "push", "pull", "pressure", "friction", "gravitational", "magnetic", "contact", "noncontact"],
     "content": "Force is a push or pull. Contact forces (muscular, friction) need physical touch. Non-contact forces (gravitational, magnetic, electrostatic) act at a distance. Pressure = force/area."},
    {"id": "sci-8-sound", "subject": "Science", "class_range": "6-8",
     "chapter": "Sound", "topic": "Sound production and propagation",
     "keywords": ["sound", "vibration", "frequency", "amplitude", "pitch", "loudness", "medium", "ear"],
     "content": "Sound is produced by vibrations and needs a medium (solid, liquid, gas) to travel. Frequency determines pitch (high = shrill). Amplitude determines loudness. Human ear detects 20 Hz — 20,000 Hz."},
    {"id": "sci-8-crop", "subject": "Science", "class_range": "6-8",
     "chapter": "Crop Production and Management", "topic": "Agriculture practices",
     "keywords": ["crop", "agriculture", "soil", "irrigation", "fertilizer", "pesticide", "harvest", "kharif", "rabi"],
     "content": "Kharif crops are sown in rainy season (rice, maize). Rabi crops in winter (wheat, mustard). Practices: ploughing, sowing, adding manure/fertilizers, irrigation, weeding, harvesting, storage."},

    # Science: Class 9-10
    {"id": "sci-9-matter", "subject": "Science", "class_range": "9-10",
     "chapter": "Matter in Our Surroundings", "topic": "States of matter",
     "keywords": ["matter", "solid", "liquid", "gas", "particle", "diffusion", "evaporation", "sublimation"],
     "content": "Matter has mass and occupies space. Particles are in constant motion. Solids have fixed shape/volume, liquids take container shape, gases fill container. Evaporation causes cooling. Sublimation (solid to gas directly)."},
    {"id": "sci-9-atoms", "subject": "Science", "class_range": "9-10",
     "chapter": "Atoms and Molecules", "topic": "Atomic structure and bonding",
     "keywords": ["atom", "molecule", "element", "compound", "atomic mass", "mole", "Avogadro"],
     "content": "Atoms are the smallest unit of matter. Molecules are groups of atoms. Elements contain one type of atom. Compounds contain different elements chemically bonded. 1 mole = 6.022 x 10^23 particles."},
    {"id": "sci-9-cell", "subject": "Science", "class_range": "9-10",
     "chapter": "The Fundamental Unit of Life", "topic": "Cell structure",
     "keywords": ["cell", "nucleus", "cytoplasm", "membrane", "organelle", "mitochondria", "ribosome", "prokaryotic", "eukaryotic"],
     "content": "Cell is the basic unit of life. Prokaryotic cells (bacteria) lack nucleus. Eukaryotic cells have nucleus and organelles: mitochondria (powerhouse), ribosomes (protein synthesis), ER, Golgi apparatus."},
    {"id": "sci-9-motion-laws", "subject": "Science", "class_range": "9-10",
     "chapter": "Force and Laws of Motion", "topic": "Newton's laws",
     "keywords": ["Newton", "inertia", "force", "acceleration", "momentum", "reaction", "third law", "first law"],
     "content": "Newton's First Law: objects resist change in motion (inertia). Second Law: F = ma. Third Law: every action has equal and opposite reaction. Momentum = mass x velocity."},
    {"id": "sci-9-gravitation", "subject": "Science", "class_range": "9-10",
     "chapter": "Gravitation", "topic": "Gravity and free fall",
     "keywords": ["gravity", "gravitation", "free fall", "mass", "weight", "acceleration", "g", "9.8"],
     "content": "Universal law of gravitation: every object attracts every other with force proportional to product of masses and inversely proportional to square of distance. g = 9.8 m/s^2 on Earth. Weight = mg."},
    {"id": "sci-10-chemical", "subject": "Science", "class_range": "9-10",
     "chapter": "Chemical Reactions and Equations", "topic": "Chemical reactions",
     "keywords": ["chemical reaction", "equation", "reactant", "product", "combination", "decomposition", "displacement", "redox", "oxidation", "reduction"],
     "content": "Chemical reactions involve reactants forming products. Types: combination (A+B=AB), decomposition (AB=A+B), displacement (AB+C=AC+B), double displacement, and redox (oxidation = loss of electrons, reduction = gain)."},
    {"id": "sci-10-electricity", "subject": "Science", "class_range": "9-10",
     "chapter": "Electricity", "topic": "Current, voltage, resistance",
     "keywords": ["electricity", "current", "voltage", "resistance", "Ohm", "circuit", "series", "parallel", "power"],
     "content": "Ohm's law: V = IR. Resistors in series: R_total = R1 + R2; in parallel: 1/R_total = 1/R1 + 1/R2. Power = VI = I^2R = V^2/R. Heating effect: H = I^2Rt."},
    {"id": "sci-10-light", "subject": "Science", "class_range": "9-10",
     "chapter": "Light: Reflection and Refraction", "topic": "Mirrors, lenses and refraction",
     "keywords": ["light", "reflection", "refraction", "mirror", "lens", "focal length", "magnification", "Snell"],
     "content": "Spherical mirrors: concave (converging), convex (diverging). Mirror formula: 1/f = 1/u + 1/v. Refraction: bending of light when changing medium. Snell's law: n1 sin theta1 = n2 sin theta2."},

    # Mathematics: Class 6-8
    {"id": "math-6-numbers", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Knowing Our Numbers", "topic": "Place value and estimation",
     "keywords": ["number", "place value", "estimation", "rounding", "Indian system", "International system"],
     "content": "Place value: ones, tens, hundreds, thousands, ten thousands, lakhs, crores. Indian numbering system uses lakhs and crores. International uses millions and billions."},
    {"id": "math-6-fractions", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Fractions and Decimals", "topic": "Fraction operations",
     "keywords": ["fraction", "decimal", "numerator", "denominator", "equivalent", "improper", "mixed"],
     "content": "Fractions represent parts of a whole. Proper (N < D), improper (N > D), mixed (whole + proper). Add/subtract: find common denominator. Multiply: multiply numerators and denominators. Divide: multiply by reciprocal."},
    {"id": "math-7-integers", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Integers", "topic": "Addition, subtraction of integers",
     "keywords": ["integer", "positive", "negative", "number line", "absolute value", "addition", "subtraction"],
     "content": "Integers are whole numbers and their negatives. On a number line, right is positive, left is negative. Adding: same sign = add and keep sign; different sign = subtract and take sign of larger."},
    {"id": "math-8-quadrilaterals", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Understanding Quadrilaterals", "topic": "Quadrilateral types and properties",
     "keywords": ["quadrilateral", "parallelogram", "rectangle", "rhombus", "square", "trapezium", "diagonal"],
     "content": "Quadrilaterals: trapezium (one pair parallel), parallelogram (both pairs parallel), rectangle (right angles), rhombus (equal sides), square (equal sides + right angles). Sum of interior angles = 360 degrees."},

    # Mathematics: Class 9-10
    {"id": "math-9-polynomials", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Polynomials", "topic": "Polynomial operations and factorization",
     "keywords": ["polynomial", "degree", "coefficient", "factor", "identity", "zero", "remainder theorem"],
     "content": "Polynomials are algebraic expressions with non-negative integer exponents. Degree = highest exponent. Remainder theorem: p(a) is remainder when p(x) is divided by (x-a). Factor theorem: if p(a) = 0 then (x-a) is a factor."},
    {"id": "math-9-triangles", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Triangles", "topic": "Congruence and properties",
     "keywords": ["triangle", "congruence", "SSS", "SAS", "ASA", "RHS", "inequality", "isosceles"],
     "content": "Triangle congruence: SSS (all sides equal), SAS (two sides + included angle), ASA (two angles + included side), RHS (right angle, hypotenuse, side). Isosceles: base angles equal. Triangle inequality: sum of any two sides > third side."},
    {"id": "math-10-trigonometry", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Introduction to Trigonometry", "topic": "Trigonometric ratios",
     "keywords": ["trigonometry", "sine", "cosine", "tangent", "angle", "right triangle", "Pythagoras"],
     "content": "In a right triangle: sin = opposite/hypotenuse, cos = adjacent/hypotenuse, tan = opposite/adjacent = sin/cos. Pythagoras theorem: a^2 + b^2 = c^2. sin^2 + cos^2 = 1."},
    {"id": "math-10-statistics", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Statistics", "topic": "Mean, median, mode",
     "keywords": ["statistics", "mean", "median", "mode", "data", "frequency", "average", "range"],
     "content": "Mean = sum of observations / number of observations. Median: middle value when data is arranged in order. Mode: most frequent value. Range = highest - lowest."},
    {"id": "math-10-probability", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Probability", "topic": "Basic probability",
     "keywords": ["probability", "event", "outcome", "favorable", "random", "chance"],
     "content": "Probability = favorable outcomes / total outcomes. Range: 0 to 1. 0 = impossible, 1 = certain. Examples: coin toss P(head) = 1/2, die roll P(6) = 1/6, card P(ace) = 4/52 = 1/13."},
]
