"""NCERT/Haryana Board curriculum data for RAG retrieval."""

CURRICULUM = [
    # ═══════════════════════════════════════════════
    # SCIENCE: Class 6-8
    # ═══════════════════════════════════════════════
    {"id": "sci-6-food", "subject": "Science", "class_range": "6-8",
     "chapter": "Food: Where Does It Come From?", "topic": "Food sources and nutrition",
     "keywords": ["food", "source", "plant", "animal", "ingredient", "crop", "nutrition", "herbivore", "carnivore", "omnivore"],
     "content": "Food comes from plants (grains, vegetables, fruits) and animals (milk, eggs, meat). Plants make their own food through photosynthesis. Animals depend on plants directly or indirectly. Herbivores eat only plants, carnivores eat only animals, omnivores eat both."},
    {"id": "sci-6-components", "subject": "Science", "class_range": "6-8",
     "chapter": "Components of Food", "topic": "Nutrients and balanced diet",
     "keywords": ["nutrient", "carbohydrate", "protein", "fat", "vitamin", "mineral", "roughage", "balanced diet", "deficiency"],
     "content": "Food contains nutrients: carbohydrates (energy), proteins (growth), fats (energy storage), vitamins and minerals (protection), and roughage (digestion). A balanced diet has all nutrients in right proportions. Deficiency diseases: scurvy (Vitamin C), rickets (Vitamin D), anaemia (iron)."},
    {"id": "sci-6-separation", "subject": "Science", "class_range": "6-8",
     "chapter": "Separation of Substances", "topic": "Separation methods",
     "keywords": ["separation", "filtration", "evaporation", "distillation", "sieving", "magnet", "threshing", "winnowing"],
     "content": "Separation methods based on properties: sieving (size), filtration (solubility), evaporation (soluble solid from liquid),磁铁 (magnetic), distillation (boiling point), decantation (density). Threshing separates grain from stalks, winnowing separates grain from chaff."},
    {"id": "sci-6-fiber", "subject": "Science", "class_range": "6-8",
     "chapter": "Fabric Gathering", "topic": "Fibres and fabrics",
     "keywords": ["fibre", "fabric", "cotton", "wool", "silk", "jute", "spinning", "weaving"],
     "content": "Fibres are natural (cotton, wool, silk, jute) or synthetic (nylon, polyester). Cotton grows in bolls, wool comes from sheep, silk from silkworms. Spinning converts fibre to yarn, weaving interlaces yarns to make fabric."},
    {"id": "sci-6-light", "subject": "Science", "class_range": "6-8",
     "chapter": "Light, Shadows and Reflections", "topic": "Light behavior and shadows",
     "keywords": ["light", "shadow", "reflection", "mirror", "opaque", "transparent", "translucent", "luminous", "non-luminous"],
     "content": "Light travels in straight lines. Luminous objects emit light (sun, bulb), non-luminous reflect it. Opaque objects block light creating shadows. Transparent objects let all light through, translucent let some through. Mirrors reflect light — plane mirrors form virtual, laterally inverted images."},
    {"id": "sci-6-electricity", "subject": "Science", "class_range": "6-8",
     "chapter": "Electricity and Circuits", "topic": "Electric circuits and components",
     "keywords": ["electricity", "circuit", "battery", "bulb", "switch", "conductor", "insulator", "cell", "current"],
     "content": "An electric circuit needs a cell/battery (power source), wires (conductors), a bulb (load), and a switch. Conductors (metals) allow current to flow; insulators (rubber, plastic) do not. A closed circuit is needed for current flow. Current flows from positive to negative terminal."},
    {"id": "sci-6-plants", "subject": "Science", "class_range": "6-8",
     "chapter": "Getting to Know Plants", "topic": "Plant parts and functions",
     "keywords": ["plant", "root", "stem", "leaf", "flower", "photosynthesis", "chlorophyll", "xylem", "phloem", "herb", "shrub", "tree"],
     "content": "Plants have roots (anchoring, absorption), stems (support, transport), leaves (photosynthesis using chlorophyll), and flowers (reproduction). Herbs have soft stems, shrubs have woody stems, trees have tall hard trunks. Xylem transports water up, phloem transports food down."},
    {"id": "sci-7-nutrition", "subject": "Science", "class_range": "6-8",
     "chapter": "Nutrition in Plants and Animals", "topic": "Photosynthesis and digestion",
     "keywords": ["photosynthesis", "chlorophyll", "autotroph", "heterotroph", "digestion", "stomata", "parasite", "symbiosis", "saprophyte"],
     "content": "Plants are autotrophs — they make food via photosynthesis: 6CO2 + 6H2O + sunlight → C6H12O6 + 6O2. Stomata on leaves allow gas exchange. Animals are heterotrophs. Some organisms are parasites (Cuscuta), some are saprophytes (fungi), some have symbiotic relationships."},
    {"id": "sci-7-heat", "subject": "Science", "class_range": "6-8",
     "chapter": "Heat", "topic": "Temperature and heat transfer",
     "keywords": ["heat", "temperature", "thermometer", "conduction", "convection", "radiation", "Celsius", "conductor", "insulator"],
     "content": "Heat is energy that flows from hot to cold. Temperature measures hotness in Celsius. Thermometers use mercury/alcohol expansion. Heat transfers by conduction (solids, direct contact), convection (fluids, circulation), and radiation (no medium needed, like sunlight). Metals are good conductors; air, wood, plastic are insulators."},
    {"id": "sci-7-acids", "subject": "Science", "class_range": "6-8",
     "chapter": "Acids, Bases and Salts", "topic": "Acids, bases, indicators, neutralization",
     "keywords": ["acid", "base", "salt", "indicator", "litmus", "pH", "neutralization", "turmeric", "china rose"],
     "content": "Acids taste sour (lemon-citric, vinegar-acetic). Bases taste bitter (soap, baking soda). Indicators: litmus (blue→red in acid, red→blue in base), turmeric (yellow→red in base), china rose (pink in acid, green in base). Neutralization: acid + base → salt + water."},
    {"id": "sci-7-weather", "subject": "Science", "class_range": "6-8",
     "chapter": "Weather, Climate and Adaptations", "topic": "Weather, climate, adaptations",
     "keywords": ["weather", "climate", "temperature", "rainfall", "humidity", "adaptation", "polar", "tropical", "monsoon"],
     "content": "Weather is day-to-day conditions (temperature, rainfall, humidity). Climate is average weather over years. India has tropical monsoon climate. Adaptations: polar animals have thick fur, desert animals store water, tropical animals have broad leaves. Rain gauge measures rainfall, thermometer measures temperature."},
    {"id": "sci-7-respiration", "subject": "Science", "class_range": "6-8",
     "chapter": "Respiration in Organisms", "topic": "Respiration types and breathing",
     "keywords": ["respiration", "breathing", "oxygen", "carbon dioxide", "aerobic", "anaerobic", "lungs", "gills", "trachea"],
     "content": "Respiration breaks down food to release energy. Aerobic (with O2): glucose + O2 → CO2 + H2O + 36 ATP. Anaerobic (without O2): glucose → ethanol + CO2 + 2 ATP (in yeast/muscles). Humans breathe through lungs (diaphragm contracts). Fish use gills, earthworms use skin, insects use trachea."},
    {"id": "sci-8-motion", "subject": "Science", "class_range": "6-8",
     "chapter": "Motion and Measurement of Distances", "topic": "Types of motion and measurement",
     "keywords": ["motion", "rectilinear", "circular", "periodic", "oscillatory", "metre", "ruler", "measuring tape"],
     "content": "Motion is change in position relative to a reference point. Types: rectilinear (straight line), circular (around a center), periodic (repeating at regular intervals), oscillatory (to-and-fro). SI unit of length is metre. 1 km = 1000 m, 1 m = 100 cm."},
    {"id": "sci-8-force", "subject": "Science", "class_range": "6-8",
     "chapter": "Force and Pressure", "topic": "Force types, pressure, buoyancy",
     "keywords": ["force", "push", "pull", "pressure", "friction", "gravitational", "magnetic", "buoyancy", "atmospheric"],
     "content": "Force is a push or pull that changes motion. Contact forces: muscular, friction, tension. Non-contact: gravitational, magnetic, electrostatic. Pressure = force/area. Liquids exert pressure in all directions. Buoyancy: upward force on submerged objects. Atmospheric pressure: weight of air column."},
    {"id": "sci-8-sound", "subject": "Science", "class_range": "6-8",
     "chapter": "Sound", "topic": "Sound production, propagation, pitch, loudness",
     "keywords": ["sound", "vibration", "frequency", "amplitude", "pitch", "loudness", "medium", "ear", "sonar", "infrasound", "ultrasound"],
     "content": "Sound is produced by vibrations. Needs medium (solid/liquid/gas) — no sound in vacuum. Frequency (Hz) determines pitch: high frequency = high pitch. Amplitude determines loudness. Human ear: 20 Hz–20,000 Hz. Below 20 Hz = infrasound (elephants), above 20,000 Hz = ultrasound (bats). Speed: ~343 m/s in air, ~1480 m/s in water."},
    {"id": "sci-8-crop", "subject": "Science", "class_range": "6-8",
     "chapter": "Crop Production and Management", "topic": "Agriculture practices",
     "keywords": ["crop", "agriculture", "soil", "irrigation", "fertilizer", "pesticide", "harvest", "kharif", "rabi", "zaid"],
     "content": "Kharif crops: sown in rainy season (June-Oct) — rice, maize, cotton, sugarcane. Rabi crops: sown in winter (Oct-March) — wheat, mustard, pea, gram. Zaid: summer crops — watermelon, cucumber. Practices: irrigation (drip, sprinkler), manure vs fertilizer, weeding, harvesting, storage."},
    {"id": "sci-8-microbes", "subject": "Science", "class_range": "6-8",
     "chapter": "Microorganisms: Friend and Foe", "topic": "Microbes, diseases, food preservation",
     "keywords": ["microorganism", "bacteria", "virus", "fungus", "decomposition", "fermentation", "antibiotic", "preservation", "pasteurization"],
     "content": "Microorganisms: bacteria (single cell), viruses (need host), fungi (yeast, mould), protozoa (amoeba). Useful: decomposition, fermentation (curd, bread, alcohol), antibiotics (penicillin). Harmful: diseases (cholera, malaria, COVID). Food preservation: salting, canning, pasteurization, drying."},
    {"id": "sci-8-combustion", "subject": "Science", "class_range": "6-8",
     "chapter": "Combustion and Flame", "topic": "Combustion types, flame, fire safety",
     "keywords": ["combustion", "flame", "fire", "ignition", "fuel", "oxygen", "inflammable", "extinguisher"],
     "content": "Combustion: burning of substance in presence of oxygen. Types: complete (produces CO2 + H2O), incomplete (produces CO — toxic), spontaneous (at room temp). Flame zones: outer (hottest, blue), middle (yellow, luminous), inner (unburnt wax vapour). Fire extinguishers: CO2 (electrical), water (wood), foam (oil)."},

    # ═══════════════════════════════════════════════
    # SCIENCE: Class 9-10
    # ═══════════════════════════════════════════════
    {"id": "sci-9-matter", "subject": "Science", "class_range": "9-10",
     "chapter": "Matter in Our Surroundings", "topic": "States of matter and changes",
     "keywords": ["matter", "solid", "liquid", "gas", "particle", "diffusion", "evaporation", "sublimation", "melting", "boiling"],
     "content": "Matter has mass and volume. Particles in constant motion. Solids: fixed shape, strong bonds. Liquids: flow, take container shape. Gases: fill container, weak bonds. Changes: melting (s→l), boiling (l→g), evaporation (surface l→g), sublimation (s→g directly). Evaporation cooling: particles with high energy escape."},
    {"id": "sci-9-is matter", "subject": "Science", "class_range": "9-10",
     "chapter": "Is Matter Around Us Pure?", "topic": "Mixtures, solutions, separation",
     "keywords": ["mixture", "solution", "solute", "solvent", "suspension", "colloid", "saturated", "concentration", "tyndall"],
     "content": "Pure substances: elements and compounds. Mixtures: homogeneous (solutions — salt water) and heterogeneous (sand + water). Solutions: solute dissolved in solvent. Saturated solution: no more solute can dissolve. Tyndall effect: light scattering in colloids (milk, fog)."},
    {"id": "sci-9-atoms", "subject": "Science", "class_range": "9-10",
     "chapter": "Atoms and Molecules", "topic": "Atomic structure, mole concept",
     "keywords": ["atom", "molecule", "element", "compound", "atomic mass", "mole", "Avogadro", "ion", "valency"],
     "content": "Atoms: smallest unit of element. Nucleus (protons + neutrons) + electrons orbiting. Molecules: group of atoms (H2O = 2H + 1O). Ions: charged atoms (Na+, Cl-). Valency: combining capacity. Mole = 6.022×10^23 particles. Atomic mass unit (amu). Law of conservation of mass."},
    {"id": "sci-9-cell", "subject": "Science", "class_range": "9-10",
     "chapter": "The Fundamental Unit of Life", "topic": "Cell structure and function",
     "keywords": ["cell", "nucleus", "cytoplasm", "membrane", "organelle", "mitochondria", "ribosome", "prokaryotic", "eukaryotic", "plasma membrane"],
     "content": "Cell = basic unit of life. Plasma membrane: selective barrier. Nucleus: controls cell, has DNA. Cytoplasm: jelly-like, organelles float. Mitochondria: powerhouse (ATP production). Ribosomes: protein synthesis. Prokaryotic: no nucleus (bacteria). Eukaryotic: nucleus present (plants, animals). Plant cells have cell wall + chloroplasts."},
    {"id": "sci-9-tissues", "subject": "Science", "class_range": "9-10",
     "chapter": "Tissues", "topic": "Plant and animal tissues",
     "keywords": ["tissue", "epithelial", "connective", "muscular", "nervous", "meristematic", "permanent", "xylem", "phloem"],
     "content": "Tissues: group of similar cells. Plant: meristematic (dividing), permanent — simple (parenchyma storage, collenchyma flexible support, sclerenchyma rigid) + complex (xylem transports water up, phloem transports food). Animal: epithelial (covering), connective (bone, blood, cartilage), muscular (voluntary/involuntary/cardiac), nervous (neurons)."},
    {"id": "sci-9-motion-laws", "subject": "Science", "class_range": "9-10",
     "chapter": "Force and Laws of Motion", "topic": "Newton's three laws",
     "keywords": ["Newton", "inertia", "force", "acceleration", "momentum", "reaction", "first law", "second law", "third law", "unbalanced"],
     "content": "First Law (Inertia): object at rest stays at rest, in motion stays in motion unless unbalanced force acts. Second Law: F = ma (force = mass × acceleration). Momentum = mv. Third Law: every action has equal opposite reaction. Conservation of momentum: m1u1 + m2u2 = m1v1 + m2v2."},
    {"id": "sci-9-gravitation", "subject": "Science", "class_range": "9-10",
     "chapter": "Gravitation", "topic": "Gravity, free fall, weight",
     "keywords": ["gravity", "gravitation", "free fall", "mass", "weight", "acceleration", "g", "9.8", "buoyancy", "Archimedes"],
     "content": "Universal gravitation: F = Gm1m2/r^2. g = 9.8 m/s^2 on Earth. Weight = mg (varies with gravity). Mass is constant. Free fall: only gravity acts. Archimedes principle: upward buoyant force = weight of displaced fluid. Relative density = density of substance / density of water."},
    {"id": "sci-9-float", "subject": "Science", "class_range": "9-10",
     "chapter": "Floatation and Archimedes Principle", "topic": "Buoyancy and density",
     "keywords": ["float", "buoyancy", "Archimedes", "density", "relative density", "upthrust", "displaced"],
     "content": "Object floats if its density < fluid density. Upthrust = weight of displaced fluid. If upthrust > weight, object floats. If upthrust < weight, object sinks. Relative density (specific gravity) = density of substance / density of water. No units."},
    {"id": "sci-10-chemical", "subject": "Science", "class_range": "9-10",
     "chapter": "Chemical Reactions and Equations", "topic": "Types of chemical reactions",
     "keywords": ["chemical reaction", "equation", "reactant", "product", "combination", "decomposition", "displacement", "redox", "oxidation", "reduction", "balanced"],
     "content": "Chemical reaction: new substances formed. Balanced equation: equal atoms on both sides. Types: combination (A+B→AB), decomposition (AB→A+B, needs heat/light/electricity), displacement (more reactive displaces less), double displacement, redox (oxidation=loss of electrons, reduction=gain). Signs: gas evolution, precipitate, color change, temperature change."},
    {"id": "sci-10-acids-bases", "subject": "Science", "class_range": "9-10",
     "chapter": "Acids, Bases and Salts", "topic": "pH scale and reactions",
     "keywords": ["acid", "base", "pH", "neutralization", "indicator", "universal indicator", "pH scale", "strong", "weak"],
     "content": "pH scale 0-14: <7 acidic, =7 neutral, >7 basic. Strong acids (HCl, H2SO4) fully dissociate; weak acids (CH3COOH) partially. Common salts: NaCl (table salt), NaHCO3 (baking soda), Na2CO3 (washing soda). Neutralization: acid + base → salt + water. Antacids neutralize excess stomach acid."},
    {"id": "sci-10-metals", "subject": "Science", "class_range": "9-10",
     "chapter": "Metals and Non-metals", "topic": "Properties and reactivity",
     "keywords": ["metal", "nonmetal", "reactivity", "corrosion", "alloy", "ductile", "malleable", "conductivity", "reactivity series"],
     "content": "Metals: lustrous, malleable, ductile, good conductors. Non-metals: brittle, poor conductors. Reactivity series: K>Na>Ca>Mg>Al>Zn>Fe>Pb>H>Cu>Ag>Au. More reactive metal displaces less reactive from salt solution. Corrosion: rusting of iron (prevent by painting, galvanizing). Alloys: mixtures (brass=Cu+Zn, bronze=Cu+Sn, steel=Fe+C)."},
    {"id": "sci-10-carbon", "subject": "Science", "class_range": "9-10",
     "chapter": "Carbon and its Compounds", "topic": "Organic chemistry basics",
     "keywords": ["carbon", "covalent bond", "hydrocarbon", "functional group", "ethanol", "ethanoic acid", "ester", "soap", "saturated", "unsaturated"],
     "content": "Carbon forms 4 covalent bonds. Catenation: carbon chains. Saturated: alkanes (single bonds, CnH2n+2). Unsaturated: alkenes (double, CnH2n), alkynes (triple, CnH2n-2). Functional groups: -OH (alcohol), -COOH (acid), -CHO (aldehyde). Ethanol: CH3CH2OH. Ethanoic acid: CH3COOH. Soaps: sodium salts of fatty acids."},
    {"id": "sci-10-life", "subject": "Science", "class_range": "9-10",
     "chapter": "Life Processes", "topic": "Nutrition, respiration, circulation, excretion",
     "keywords": ["nutrition", "respiration", "circulation", "excretion", "digestion", "heart", "kidney", "hemoglobin", "ATP", "villi"],
     "content": "Nutrition: autotrophic (photosynthesis) vs heterotrophic (digestion). Respiration: aerobic (36 ATP/glucose) vs anaerobic (2 ATP). Digestion: mouth(starch)→stomach(protein)→small intestine(fat, absorption via villi). Circulation: heart pumps blood, hemoglobin carries O2. Excretion: kidneys filter blood → urine."},
    {"id": "sci-10-control", "subject": "Science", "class_range": "9-10",
     "chapter": "Control and Coordination", "topic": "Nervous system and hormones",
     "keywords": ["neuron", "nerve", "brain", "reflex", "hormone", "endocrine", "synapse", "spinal cord", "coordination"],
     "content": "Nervous system: electrical signals via neurons. Brain: cerebrum (thinking), cerebellum (balance), medulla (involuntary). Reflex arc: receptor→sensory neuron→spinal cord→motor neuron→effector (fastest response). Endocrine: hormones (chemical messengers). Pituitary: master gland. Thyroid: metabolism. Insulin: blood sugar control. Adrenaline: fight-or-flight."},
    {"id": "sci-10-electricity", "subject": "Science", "class_range": "9-10",
     "chapter": "Electricity", "topic": "Current, voltage, resistance, power",
     "keywords": ["electricity", "current", "voltage", "resistance", "Ohm", "circuit", "series", "parallel", "power", "heating"],
     "content": "Ohm's law: V = IR. Current: flow of charge (I = Q/t). Series: R_total = R1+R2+... (same current). Parallel: 1/R_total = 1/R1+1/R2+... (same voltage). Power: P = VI = I²R = V²/R. Heating: H = I²Rt. Domestic circuits: parallel wiring, fuse for safety."},
    {"id": "sci-10-light", "subject": "Science", "class_range": "9-10",
     "chapter": "Light: Reflection and Refraction", "topic": "Mirrors, lenses, refraction",
     "keywords": ["light", "reflection", "refraction", "mirror", "lens", "focal length", "magnification", "Snell", "concave", "convex"],
     "content": "Reflection: angle of incidence = angle of reflection. Concave mirror: converges light (shaving, headlight). Convex mirror: diverges (rear-view). Mirror formula: 1/f = 1/v + 1/u. Refraction: bending when changing medium. Snell's law: n1 sin θ1 = n2 sin θ2. Convex lens: converges (magnifying glass). Concave lens: diverges."},

    # ═══════════════════════════════════════════════
    # MATHEMATICS: Class 6-8
    # ═══════════════════════════════════════════════
    {"id": "math-6-numbers", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Knowing Our Numbers", "topic": "Place value, large numbers",
     "keywords": ["number", "place value", "estimation", "rounding", "Indian system", "International system", "lakh", "crore"],
     "content": "Place value: ones, tens, hundreds, thousands, ten thousands, lakhs, ten lakhs, crores. Indian system: lakhs and crores. International: millions and billions. Roman numerals: I=1, V=5, X=10, L=50, C=100, D=500, M=1000. Estimation: rounding to nearest 10, 100, 1000."},
    {"id": "math-6-fractions", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Fractions and Decimals", "topic": "Fraction and decimal operations",
     "keywords": ["fraction", "decimal", "numerator", "denominator", "equivalent", "improper", "mixed", "reciprocal"],
     "content": "Fractions: parts of a whole. Proper (N<D), improper (N>D), mixed (whole+proper). Add/subtract: common denominator. Multiply: numerators × numerators. Divide: multiply by reciprocal. Decimals: tenths, hundredths. Multiply decimals: ignore decimal point, then place it. Divide: convert to fraction."},
    {"id": "math-6-geometry", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Basic Geometrical Ideas", "topic": "Shapes, angles, and figures",
     "keywords": ["point", "line", "ray", "angle", "triangle", "quadrilateral", "circle", "polygon", "diameter", "radius"],
     "content": "Point (position), line (extends both ways), line segment (fixed), ray (one direction). Angle: formed by two rays from common vertex. Types: acute (<90°), right (=90°), obtuse (>90°), straight (=180°). Triangle: 3 sides. Quadrilateral: 4 sides. Circle: set of points equidistant from center."},
    {"id": "math-7-integers", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Integers", "topic": "Positive and negative numbers",
     "keywords": ["integer", "positive", "negative", "number line", "absolute value", "addition", "subtraction"],
     "content": "Integers: whole numbers and negatives (...-3,-2,-1,0,1,2,3...). Number line: right = positive, left = negative. Adding same sign: add, keep sign. Different sign: subtract, take sign of larger. Subtracting: add the opposite. Absolute value: distance from zero (always positive)."},
    {"id": "math-7-fractions", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Fractions and Decimals", "topic": "Operations on fractions",
     "keywords": ["fraction", "multiplication", "division", "reciprocal", "mixed fraction", "decimal"],
     "content": "Multiply fractions: numerator × numerator, denominator × denominator. Divide: multiply by reciprocal of divisor. Mixed to improper: (whole × denominator + numerator)/denominator. Decimal × 10, 100, 1000: move decimal point right. Decimal ÷ 10, 100, 1000: move decimal point left."},
    {"id": "math-7-equations", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Simple Equations", "topic": "Solving linear equations",
     "keywords": ["equation", "variable", "solve", "algebra", "expression", "LHS", "RHS", "transpose"],
     "content": "Equation: LHS = RHS. Variable: unknown quantity (x, y). To solve: isolate variable by performing same operation on both sides. Transpose: move term to other side, change sign. Example: 2x + 5 = 13 → 2x = 8 → x = 4. Verify: substitute back into original equation."},
    {"id": "math-7-perimeter", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Perimeter and Area", "topic": "Measurement formulas",
     "keywords": ["perimeter", "area", "square", "rectangle", "triangle", "circle", "circumference", "parallelogram"],
     "content": "Perimeter = total boundary length. Square: P=4s, A=s². Rectangle: P=2(l+b), A=l×b. Triangle: A=½×base×height. Parallelogram: A=base×height. Circle: C=2πr=πd, A=πr². 1 cm² = 100 mm², 1 m² = 10,000 cm²."},
    {"id": "math-8-rational", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Rational Numbers", "topic": "Properties and operations",
     "keywords": ["rational", "fraction", "commutative", "associative", "distributive", "identity", "inverse", "closure"],
     "content": "Rational numbers: p/q where q≠0. Properties: commutative (a+b=b+a), associative ((a+b)+c=a+(b+c)), distributive (a×(b+c)=a×b+a×c). Additive identity=0, multiplicative identity=1. Additive inverse=-a, multiplicative inverse=1/a. Closure: sum/product of rationals is rational."},
    {"id": "math-8-quares", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Squares and Square Roots", "topic": "Perfect squares and roots",
     "keywords": ["square", "square root", "perfect square", "Pythagoras", "radical"],
     "content": "Perfect squares: 1,4,9,16,25,36,49,64,81,100... Properties: end in 0,1,4,5,6,9. Never end in 2,3,7,8. Square root: inverse of squaring. √144=12. Pythagoras theorem: in right triangle, a²+b²=c². Finding square root: prime factorization or long division method."},
    {"id": "math-8-cubes", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Cubes and Cube Roots", "topic": "Perfect cubes and roots",
     "keywords": ["cube", "cube root", "perfect cube"],
     "content": "Cube: number × number × number (n³). Perfect cubes: 1,8,27,64,125,216... Cube root: ∛64=4. Properties: cubes of even numbers are even, cubes of odd numbers are odd. Sum of first n odd numbers = n³."},
    {"id": "math-8-quads", "subject": "Mathematics", "class_range": "6-8",
     "chapter": "Understanding Quadrilaterals", "topic": "Types and properties",
     "keywords": ["quadrilateral", "parallelogram", "rectangle", "rhombus", "square", "trapezium", "diagonal", "kite"],
     "content": "Quadrilaterals: trapezium (1 pair parallel), parallelogram (2 pairs parallel), rectangle (parallelogram + right angles), rhombus (parallelogram + equal sides), square (rectangle + rhombus), kite (2 pairs equal adjacent sides). Sum of interior angles = 360°. Diagonals of parallelogram bisect each other."},

    # ═══════════════════════════════════════════════
    # MATHEMATICS: Class 9-10
    # ═══════════════════════════════════════════════
    {"id": "math-9-numbers", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Number Systems", "topic": "Real numbers and irrationals",
     "keywords": ["real number", "rational", "irrational", "sqrt", "pi", "decimal", "expansion", "Euclid"],
     "content": "Real numbers: rational (terminating/repeating decimal) and irrational (non-repeating infinite decimal). √2, √3, π are irrational. Euclid's division lemma: a = bq + r. Fundamental theorem of arithmetic: every composite number is product of primes. √p is irrational if p is prime."},
    {"id": "math-9-polynomials", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Polynomials", "topic": "Operations and factorization",
     "keywords": ["polynomial", "degree", "coefficient", "factor", "identity", "zero", "remainder theorem", "factor theorem"],
     "content": "Polynomial: expression with non-negative integer exponents. Degree: highest exponent. Remainder theorem: p(a) = remainder when p(x) divided by (x-a). Factor theorem: p(a)=0 → (x-a) is factor. Identities: (a+b)²=a²+2ab+b², (a-b)²=a²-2ab+b², a²-b²=(a-b)(a+b), (a+b)³=a³+3a²b+3ab²+b³."},
    {"id": "math-9-coordinate", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Coordinate Geometry", "topic": "Cartesian plane, distance formula",
     "keywords": ["coordinate", "Cartesian", "axis", "quadrant", "distance", "section formula", "midpoint"],
     "content": "Cartesian plane: x-axis (horizontal) + y-axis (vertical). Origin (0,0). Quadrants: I(+,+), II(-,+), III(-,-), IV(+,-). Distance formula: d=√((x2-x1)²+(y2-y1)²). Section formula: P divides AB in ratio m:n. Midpoint: ((x1+x2)/2, (y1+y2)/2)."},
    {"id": "math-9-linear", "subject": "Mathematics", "class_range": "9-10",
     "chapter:": "Introduction to Euclid's Geometry", "topic": "Euclid's axioms and postulates",
     "keywords": ["Euclid", "axiom", "postulate", "theorem", "proof", "geometry"],
     "content": "Euclid's axioms: things equal to same thing are equal to one another, wholes are greater than parts. 5 postulates: straight line between two points, extend infinitely, circle with center/radius, all right angles equal, parallel postulate. Axioms are universal truths, postulates are specific to geometry."},
    {"id": "math-9-triangles", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Triangles", "topic": "Congruence and similarity",
     "keywords": ["triangle", "congruence", "SSS", "SAS", "ASA", "RHS", "similarity", "AAA", "inequality"],
     "content": "Congruent: same shape and size. Conditions: SSS, SAS, ASA, RHS. Similar: same shape, different size. Conditions: AAA, SSS ratio, SAS ratio. Triangle inequality: sum of any two sides > third side. Properties: exterior angle = sum of two opposite interior angles. Sum of angles = 180°."},
    {"id": "math-9-quads", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Quadrilaterals", "topic": "Properties and midpoint theorem",
     "keywords": ["quadrilateral", "parallelogram", "midpoint", "diagonal", "bisect", "rhombus"],
     "content": "Parallelogram: opposite sides parallel and equal, opposite angles equal, diagonals bisect each other. Rectangle: all parallelogram properties + right angles + equal diagonals. Rhombus: all parallelogram properties + all sides equal + diagonals perpendicular. Square: rectangle + rhombus. Midpoint theorem: line joining midpoints of two sides is parallel to third side and half its length."},
    {"id": "math-10-trig", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Introduction to Trigonometry", "topic": "Trigonometric ratios and identities",
     "keywords": ["trigonometry", "sine", "cosine", "tangent", "angle", "right triangle", "Pythagoras", "identity"],
     "content": "In right triangle: sin θ = opp/hyp, cos θ = adj/hyp, tan θ = opp/adj = sin/cos. csc = 1/sin, sec = 1/cos, cot = 1/tan. Pythagoras: a²+b²=c². Identities: sin²θ+cos²θ=1, 1+tan²θ=sec²θ, 1+cot²θ=csc²θ. Standard angles: 0°,30°,45°,60°,90°."},
    {"id": "math-10-quad", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Quadratic Equations", "topic": "Solving and discriminant",
     "keywords": ["quadratic", "equation", "discriminant", "factorization", "completing square", "formula", "roots"],
     "content": "Quadratic: ax²+bx+c=0. Methods: factorization, completing square, quadratic formula: x=(-b±√(b²-4ac))/2a. Discriminant D=b²-4ac: D>0 (2 real roots), D=0 (1 repeated root), D<0 (no real roots, complex). Sum of roots = -b/a, product = c/a."},
    {"id": "math-10-circles", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Circles", "topic": "Theorems and tangent properties",
     "keywords": ["circle", "radius", "tangent", "secant", "chord", "theorem", "subtend", "inscribed", "cyclic"],
     "content": "Tangent ⊥ radius at point of contact. Two tangents from external point are equal. Angle at center = 2× angle at circumference (same arc). Angles in same segment equal. Angle in semicircle = 90°. Cyclic quadrilateral: opposite angles supplementary. Tangent-secant: PT² = PA × PB."},
    {"id": "math-10-statistics", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Statistics", "topic": "Mean, median, mode, cumulative frequency",
     "keywords": ["statistics", "mean", "median", "mode", "data", "frequency", "cumulative", "ogive"],
     "content": "Mean: sum/count. Median: middle value. Mode: most frequent. For grouped data: mean=Σfx/Σf. Median class: based on cumulative frequency. Mode formula: L + [(f1-f0)/(2f1-f0-f2)] × h. Cumulative frequency ogive: used to find median graphically."},
    {"id": "math-10-probability", "subject": "Mathematics", "class_range": "9-10",
     "chapter": "Probability", "topic": "Basic probability and events",
     "keywords": ["probability", "event", "outcome", "favorable", "random", "certain", "impossible"],
     "content": "Probability P(E) = favorable outcomes / total outcomes. 0 ≤ P ≤ 1. P(certain)=1, P(impossible)=0. Complementary: P(not E) = 1-P(E). Coin: P(head)=1/2. Die: P(6)=1/6. Cards: P(ace)=4/52=1/13. P(A or B) = P(A)+P(B) if mutually exclusive."},
]
